default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: home_cure_lab_development

test:
  <<: *default
  database: home_cure_lab_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
